#pragma once

// Auto-generated by flasher build endpoint. Do not edit manually.
#define FW_DEFAULT_NAME "front"
#define FW_DEFAULT_TYPE "relay_switch"
#define FW_DEFAULT_PASSCODE "Madness01"
#define FW_DEFAULT_WIFI_SSID "8bb"
#define FW_DEFAULT_WIFI_PASS "Arcade123..."
#define FW_DEFAULT_AP_SSID "8bb-setup"
#define FW_DEFAULT_AP_PASS "Madness01"
#define FW_DEFAULT_USE_STATIC_IP 0
#define FW_DEFAULT_STATIC_IP ""
#define FW_DEFAULT_GATEWAY ""
#define FW_DEFAULT_SUBNET_MASK ""
#define FW_DEFAULT_OTA_KEY "8bb-change-this-ota-key"
#define FW_DEFAULT_RELAY_COUNT 4
#define FW_DEFAULT_RELAY_GPIO_1 12
#define FW_DEFAULT_RELAY_GPIO_2 13
#define FW_DEFAULT_RELAY_GPIO_3 14
#define FW_DEFAULT_RELAY_GPIO_4 15
#define FW_DEFAULT_RELAY_GPIO_5 -1
#define FW_DEFAULT_RELAY_GPIO_6 -1
#define FW_DEFAULT_RELAY_GPIO_7 -1
#define FW_DEFAULT_RELAY_GPIO_8 -1
